# Generated by Django 5.1.7 on 2025-03-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("asunto", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "icono",
                    models.CharField(
                        help_text="Nombre de la clase de Font Awesome (ej: 'fa-python')",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tecnologías",
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("descripcion", models.TextField()),
                ("imagen_principal", models.ImageField(upload_to="proyectos/")),
                ("url_github", models.URLField(blank=True, null=True)),
                ("url_demo", models.URLField(blank=True, null=True)),
                ("destacado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to="web.categoria",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="proyectos", to="web.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagenProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="proyectos/galeria/")),
                ("titulo", models.CharField(blank=True, max_length=100)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="web.proyecto",
                    ),
                ),
            ],
        ),
    ]
